########################################################### 
##########          Plugin Dungeon               ########## 
##########          Config By DoneQ              ########## 
###########################################################
########################################################### 

#####################   Items Config   ####################


######## List Of Items
## 
item_list:
  - 'miecz1'
  - 'zbroja1'
#  - 'zbroja2'
#  - 'zbroja3'
#  - 'zbroja4'
######## Wiadomości zwrotne
## markcolor = kolor wykrzykników
## textcolor = kolor tekstu
## text = treść wiadomości
## showcounter = czy ma pokazywać ilu graczy widziało wiadomość
## counternumbercolor = kolor numeru graczy
## counterbrackletcolor = kolor nawiasów
miecz1:
  type: 'WEAPON'
  name: 'Testowy Miecz'
  material: 'DIAMOND_SWORD'
  minDmg: 1
  maxDmg: 10
  desc:
    - '1 linia'
    - '2 linia'
    - '3 linia'
zbroja1:
  type: 'ARMOR'
  name: 'Testowa Zbroja'
  material: 'DIAMOND_CHESTPLATE'
  movSpeed: 0
  addHp: 0
  addDef: 0
  desc:
    - '1 linia'
    - '2 linia'
    - '3 linia'