########################################################### 
##########          Plugin Dungeon               ########## 
##########          Config By DoneQ              ########## 
###########################################################
########################################################### 

#####################   Items Config   ####################


######## List Of Items
##  Każdy nowy item musi się tu zanjdować
item_list:
  - 'miecz1'
  - 'zbroja1'
  - 'zbroja2'
  - 'zbroja3'
  - 'zbroja4'
######## Właściwości dodanych itemów
miecz1:
  type: 'WEAPON'
  name: 'Testowy Miecz'
  material: 'DIAMOND_SWORD'
  minDmg: 1
  maxDmg: 10
  prevFalling: false
  desc:
    - '1 linia'
    - '2 linia'
    - '3 linia'
zbroja1:
  type: 'ARMOR'
  name: 'Testowa Zbroja'
  material: 'DIAMOND_CHESTPLATE'
  movSpeed: 0
  addHp: 4
  addDef: 0
  prevFalling: false
  desc:
    - '1 linia'
    - '2 linia'
    - '3 linia'
zbroja2:
  type: 'HELMET'
  name: 'Testowy Helm'
  material: 'DIAMOND_HELMET'
  movSpeed: 0
  addHp: 4
  addDef: 0
  prevFalling: false
  desc:
    - '1 linia'
    - '2 linia'
    - '3 linia'
zbroja3:
  type: 'LEGS'
  name: 'Testowe Spodnie'
  material: 'DIAMOND_LEGGINGS'
  movSpeed: 0
  addHp: 4
  addDef: 0
  prevFalling: false
  desc:
    - '1 linia'
    - '2 linia'
    - '3 linia'
zbroja4:
  type: 'BOOTS'
  name: 'Testowe Buty'
  material: 'DIAMOND_BOOTS'
  movSpeed: 0
  addHp: 4
  addDef: 0
  prevFalling: false
  desc:
    - '1 linia'
    - '2 linia'
    - '3 linia'