main: io.github.Tantol.Dungeon
name: PluginDungeon
version: 1.0
author: me
description: An Example plugin
commands:
  jebiecimatke:
    description: An example command
    usage: /jebiecimatke
  ooc:
    description: An example command
    usage: /ooc
  ic:
    description: An example command
    usage: /ic
  w:
    description: An example command
    usage: /w
  s:
    description: An example command
    usage: /s
    permission: pluginmc.pluje
    permission-message: You don't have the myplugin.mycommand permission.
  me:
    description: An example command
    usage: /me
  n:
    description: An example command
    usage: /n
    permission: rpchat.narrator.normal
    permission-message: Nie masz uprawnien aby pisac jako narrator.
  ng:
    description: An example command
    usage: /ng
    permission: rpchat.narrator.global
    permission-message: Nie masz uprawnien aby pisac jako narrator globalny.
  rpchat:
    description: An example command
    usage: /ng
  dungeon:
    description: An example command
    usage: /dungeon
  newitem:
    description: test
    usage: /newitem
  newmob:
    description: Create mob
    usage: /newmob



