main: io.github.Tantol.Dungeon
name: PluginDungeon
version: 1.0
author: me
description: An Example plugin
depend: [Vault]
commands:
  jebiecimatke:
    description: An example command
    usage: /jebiecimatke
    permission: pluginmc.pluje
    permission-message: You don't have the myplugin.mycommand permission.
  ooc:
    description: An example command
    usage: /ooc
    permission: pluginmc.pluje
    permission-message: You don't have the myplugin.mycommand permission.
  ic:
    description: An example command
    usage: /ic
    permission: pluginmc.pluje
    permission-message: You don't have the myplugin.mycommand permission.
  w:
    description: An example command
    usage: /w
    permission: pluginmc.pluje
    permission-message: You don't have the myplugin.mycommand permission.
  s:
    description: An example command
    usage: /s
    permission: pluginmc.pluje
    permission-message: You don't have the myplugin.mycommand permission.
  me:
    description: An example command
    usage: /me
    permission: pluginmc.pluje
    permission-message: You don't have the myplugin.mycommand permission.
  n:
    description: An example command
    usage: /n
    permission: pluginmc.pluje
    permission-message: You don't have the myplugin.mycommand permission.
  ng:
    description: An example command
    usage: /ng
    permission: pluginmc.pluje
    permission-message: You don't have the myplugin.mycommand permission.



